<a href="https://colab.research.google.com/github/adornkjoshy30-pixel/Healthcare-Workflow-Intelligence/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
print("Libraries laoded sucessfully")

Libraries laoded sucessfully

In [9]:
#Section 1
# goal - create a small student marks dataset
student_data = {
    "Name" : ["Asha", "Rahul", "Meera", "Arjun", "Sara", "Dev"],
    "Subject" : ["Maths", "Science", "Math", "Science", "Math", "Science"],
    "Marks": [85, 72, 91, 44, 67, 58],
    "Study_Hours": [5, 3,6,1,4,2]
}

In [10]:
student_data

{'Name': ['Asha', 'Rahul', 'Meera', 'Arjun', 'Sara', 'Dev'],
 'Subject': ['Maths', 'Science', 'Math', 'Science', 'Math', 'Science'],
 'Marks': [85, 72, 91, 44, 67, 58],
 'Study_Hours': [5, 3, 6, 1, 4, 2]}

In [11]:
df = pd.DataFrame(student_data)
df.head()

    Name  Subject  Marks  Study_Hours
0   Asha    Maths     85            5
1  Rahul  Science     72            3
2  Meera     Math     91            6
3  Arjun  Science     44            1
4   Sara     Math     67            4

In [12]:
print("First five rows")
df.head()

First five rows

    Name  Subject  Marks  Study_Hours
0   Asha    Maths     85            5
1  Rahul  Science     72            3
2  Meera     Math     91            6
3  Arjun  Science     44            1
4   Sara     Math     67            4

In [13]:
print("\nDataset shape (rows, columsn):")
print(df.shape)

Dataset shape (rows, columsn):
(6, 4)

In [14]:
print('\nColumn name:')
print(df.columns.tolist())

Column name:
['Name', 'Subject', 'Marks', 'Study_Hours']

In [15]:
print("\nONly Name and Marks:")
print(df[["Name", "Marks"]])

ONly Name and Marks:
    Name  Marks
0   Asha     85
1  Rahul     72
2  Meera     91
3  Arjun     44
4   Sara     67
5    Dev     58

In [16]:
high_scores = df[df["Marks"] >= 70]
print("\nStudents scoring 70 or above:")
print(high_scores)

Students scoring 70 or above:
    Name  Subject  Marks  Study_Hours
0   Asha    Maths     85            5
1  Rahul  Science     72            3
2  Meera     Math     91            6

In [18]:
sorted_df = df.sort_values("Marks", ascending=False)
print(sorted_df)

    Name  Subject  Marks  Study_Hours
2  Meera     Math     91            6
0   Asha    Maths     85            5
1  Rahul  Science     72            3
4   Sara     Math     67            4
5    Dev  Science     58            2
3  Arjun  Science     44            1

In [22]:
df["Result"] = np.where(df["Marks"] >= 50, "Pass", "Need support")
print("\nAdded result column:")
print(df)

Added result column:
    Name  Subject  Marks  Study_Hours        Result
0   Asha    Maths     85            5          Pass
1  Rahul  Science     72            3          Pass
2  Meera     Math     91            6          Pass
3  Arjun  Science     44            1  Need support
4   Sara     Math     67            4          Pass
5    Dev  Science     58            2          Pass

In [25]:
average_by_subject =df.groupby("Subject") ["Marks"].mean()
average_by_subject

Subject
Math       79.0
Maths      85.0
Science    58.0
Name: Marks, dtype: float64

In [27]:
df_missing = df.copy()
df_missing.loc[2, "Study_Hours"] = np.nan
df_missing

    Name  Subject  Marks  Study_Hours        Result
0   Asha    Maths     85          5.0          Pass
1  Rahul  Science     72          3.0          Pass
2  Meera     Math     91          NaN          Pass
3  Arjun  Science     44          1.0  Need support
4   Sara     Math     67          4.0          Pass
5    Dev  Science     58          2.0          Pass

In [28]:
print("\nMissing values in each column:")
print(df_missing.isnull().sum())

Missing values in each column:
Name           0
Subject        0
Marks          0
Study_Hours    1
Result         0
dtype: int64